package org.chinpon.model.entities;

public enum RoomType {
	CEREMONIES1, CEREMONIES2, HALL, STORAGE_ROOM, REST_ROOM, SECRET_PASSAGE,
	STUDY, ABISM, CRYPT, KITCHEN, DINNING_ROOM1, DINNING_ROOM2, HALL_LD,
	HALL_CENTER, HALL_RU, HALL_RD, HALL_LU, BASEMENT
}
